import React from 'react';
import { Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer';

// Note: To use Bengali/Hindi fonts, you would need to register a TTF font here.
// Font.register({ family: 'NotoSans', src: '/fonts/NotoSans-Regular.ttf' });

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: 'Helvetica',
    backgroundColor: '#ffffff'
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
    paddingBottom: 20,
    marginBottom: 30
  },
  brand: {
    fontSize: 24,
    color: '#4f46e5',
    fontWeight: 'bold'
  },
  title: {
    fontSize: 20,
    marginBottom: 20,
    color: '#111827',
    textAlign: 'center',
    fontWeight: 'bold'
  },
  section: {
    marginBottom: 25
  },
  sectionTitle: {
    fontSize: 14,
    color: '#374151',
    borderBottomWidth: 1,
    borderBottomColor: '#f3f4f6',
    paddingBottom: 5,
    marginBottom: 10,
    fontWeight: 'bold'
  },
  text: {
    fontSize: 11,
    lineHeight: 1.6,
    color: '#4b5563'
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    fontSize: 9,
    color: '#9ca3af',
    textAlign: 'center',
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
    paddingTop: 10
  }
});

interface ReportProps {
  clientNotes: string;
}

export const ReportDocument = ({ clientNotes }: ReportProps) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <Text style={styles.brand}>AstroVanta</Text>
        <Text style={{ fontSize: 10, color: '#6b7280', alignSelf: 'flex-end' }}>
          Astrological Consultation Report
        </Text>
      </View>

      <Text style={styles.title}>Comprehensive Analysis</Text>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Astrologer's Notes & Recommendations</Text>
        <Text style={styles.text}>
          {clientNotes || 'No specific notes provided for this session.'}
        </Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Disclaimer</Text>
        <Text style={{ ...styles.text, fontSize: 9, color: '#9ca3af' }}>
          This astrological report is for entertainment and guidance purposes only. 
          It should not replace professional medical, legal, or financial advice.
        </Text>
      </View>

      <Text style={styles.footer} render={({ pageNumber, totalPages }) => (
        `Generated by AstroVanta Platform • Page ${pageNumber} of ${totalPages}`
      )} />
    </Page>
  </Document>
);
